# Generated by Django 5.0.3 on 2024-05-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
