# Generated by Django 5.0.3 on 2024-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_group_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'учреждение', 'verbose_name_plural': 'Учреждения'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='group',
            name='fullname',
            field=models.CharField(default='s', max_length=100, verbose_name='Полное название группы'),
            preserve_default=False,
        ),
    ]
