# Generated by Django 5.0.3 on 2024-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_group_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='fullname',
            field=models.CharField(default='s', max_length=200, verbose_name='Полное название учреждения'),
            preserve_default=False,
        ),
    ]
