# Generated by Django 5.0.3 on 2024-05-19 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_group_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institution', verbose_name='Учреждение'),
        ),
    ]
