# Generated by Django 5.0.3 on 2024-06-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_group_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='year_of_admission',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год поступления'),
        ),
    ]
