# Generated by Django 5.0.3 on 2024-06-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_year_of_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
