# Generated by Django 5.0.3 on 2024-05-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название расположения')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название аудитории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room_photos/', verbose_name='Фотография')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='studyroom.location', verbose_name='Расположение')),
            ],
        ),
    ]
