# Generated by Django 5.0.3 on 2024-05-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'расположение', 'verbose_name_plural': 'Расположения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'помещение', 'verbose_name_plural': 'Помещения'},
        ),
    ]
