# Generated by Django 5.0.3 on 2024-05-19 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studyroom', '0002_alter_location_options_alter_room_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=0, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('week_type', models.IntegerField(choices=[(0, 'Четная'), (1, 'Нечетная'), (2, 'Обе')], default=2, verbose_name='Четность недели')),
                ('room', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_events', to='studyroom.room', verbose_name='Аудитория')),
            ],
        ),
    ]
