# Generated by Django 5.0.3 on 2024-05-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringevent',
            options={'verbose_name': 'расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
